/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/foodplater.glb -T 
Files: public/models/foodplater.glb [16.55MB] > /Users/okayadi/Developer/job-plan/meal-plan-test-main/foodplater-transformed.glb [809.28KB] (95%)
*/

import React, { useRef } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function FoodPlater(props: React.ComponentPropsWithoutRef<'group'>) {
  const { nodes } = useGLTF('/models/foodplater-transformed.glb')
  const mesh_0 = nodes.mesh_0 as THREE.Mesh
  const groupRef = useRef<THREE.Group>(null)

  useFrame((state) => {
    if (groupRef.current) {
      const elapsedTime = performance.now() * 0.001
      // 1. Idle Bobbing (slow vertical float)
      const floatY = Math.sin(elapsedTime * 1.2) * 0.04
      groupRef.current.position.y = floatY

      // 2. Slow base spin
      const baseSpin = elapsedTime * 0.08

      // 3. Interactive mouse-tracking parallax
      // state.pointer ranges from -1 to 1 based on canvas coordinate
      const targetRotationX = state.pointer.y * 0.25
      const targetRotationY = baseSpin + state.pointer.x * 0.4

      // 4. Smooth interpolation (lerp)
      groupRef.current.rotation.x = THREE.MathUtils.lerp(groupRef.current.rotation.x, targetRotationX, 0.08)
      groupRef.current.rotation.y = THREE.MathUtils.lerp(groupRef.current.rotation.y, targetRotationY, 0.08)
    }
  })

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh geometry={mesh_0.geometry} material={mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/models/foodplater-transformed.glb')
