/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/foodplater.glb -T 
Files: public/models/foodplater.glb [16.55MB] > /Users/okayadi/Developer/job-plan/meal-plan-test-main/foodplater-transformed.glb [809.28KB] (95%)
*/

import React from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'

export function FoodPlater(props: React.ComponentPropsWithoutRef<'group'>) {
  const { nodes } = useGLTF('/models/foodplater-transformed.glb')
  const mesh_0 = nodes.mesh_0 as THREE.Mesh

  // The plate stays fixed. Rotation is driven only by manual drag (OrbitControls).
  return (
    <group {...props} dispose={null}>
      <mesh geometry={mesh_0.geometry} material={mesh_0.material} castShadow receiveShadow />
    </group>
  )
}

useGLTF.preload('/models/foodplater-transformed.glb')
